using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;
using Chordata.Bex.Central.Data;
using System.Threading;

namespace Chordata.Bex.Central
{
    public partial class FrmData : Form
    {
        Tuna context;
        SemaphoreSlim load = new SemaphoreSlim(1);
        public FrmData()
        {
            InitializeComponent();
        }

        private async void FrmData_Load(object sender, EventArgs e)
        {
            await DoLoad();
            dataGridView1.Focus();
        }

        private async Task DoLoad()
        {
            await load.WaitAsync();
            try
            {
                if (context != null)
                    context.Dispose();

                context = new Tuna();
                await context.Runs.LoadAsync();
                runBindingSource.DataSource = context.Runs.Local.ToBindingList();

                await context.OPs.LoadAsync();
                oPBindingSource.DataSource = context.OPs.Local.ToBindingList();

                await context.Orders.LoadAsync();
                orderBindingSource.DataSource = context.Orders.Local.ToBindingList();

                await context.Symbols.LoadAsync();
                symbolBindingSource.DataSource = context.Symbols.Local.ToBindingList();

                await context.APIs.LoadAsync();
                aPIBindingSource.DataSource = context.APIs.Local.ToBindingList();

                dataGridView1.Refresh();
                dataGridView2.Refresh();
                dataGridView3.Refresh();
                dataGridView4.Refresh();
                dataGridView5.Refresh();
            }
            finally
            {
                load.Release();
            }

        }

        private void toolStripButtonSave_Click(object sender, EventArgs e)
        {
            Validate();
            // Save the changes to the database.
            context.SaveChanges();

            // Refresh the controls to show the values         
            // that were generated by the database.
            dataGridView1.Refresh();
            dataGridView2.Refresh();
            dataGridView3.Refresh();
            dataGridView4.Refresh();
            dataGridView5.Refresh();
        }

        private async void toolStripButtonReload_Click(object sender, EventArgs e)
        {
            ((ToolStripButton)sender).Enabled = false;
            toolStripButtonSave.Enabled = false;            
            await DoLoad();
            ((ToolStripButton)sender).Enabled = true;
            toolStripButtonSave.Enabled = true;
        }
    }
}
