//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chordata.Bex.Central.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarketHistory
    {
        public int Id { get; set; }
        public string Exchange { get; set; }
        public string Symbol { get; set; }
        public Nullable<decimal> TickerPrice { get; set; }
        public Nullable<decimal> BidPx0 { get; set; }
        public Nullable<decimal> BidPx1 { get; set; }
        public Nullable<decimal> BidPx2 { get; set; }
        public Nullable<decimal> BidPx3 { get; set; }
        public Nullable<decimal> BidPx4 { get; set; }
        public Nullable<decimal> BidPx5 { get; set; }
        public Nullable<decimal> BidPx6 { get; set; }
        public Nullable<decimal> BidPx7 { get; set; }
        public Nullable<decimal> BidPx8 { get; set; }
        public Nullable<decimal> BidPx9 { get; set; }
        public Nullable<decimal> BidSz0 { get; set; }
        public Nullable<decimal> BidSz1 { get; set; }
        public Nullable<decimal> BidSz2 { get; set; }
        public Nullable<decimal> BidSz3 { get; set; }
        public Nullable<decimal> BidSz4 { get; set; }
        public Nullable<decimal> BidSz5 { get; set; }
        public Nullable<decimal> BidSz6 { get; set; }
        public Nullable<decimal> BidSz7 { get; set; }
        public Nullable<decimal> BidSz8 { get; set; }
        public Nullable<decimal> BidSz9 { get; set; }
        public Nullable<decimal> AskPx0 { get; set; }
        public Nullable<decimal> AskPx1 { get; set; }
        public Nullable<decimal> AskPx2 { get; set; }
        public Nullable<decimal> AskPx3 { get; set; }
        public Nullable<decimal> AskPx4 { get; set; }
        public Nullable<decimal> AskPx5 { get; set; }
        public Nullable<decimal> AskPx6 { get; set; }
        public Nullable<decimal> AskPx7 { get; set; }
        public Nullable<decimal> AskPx8 { get; set; }
        public Nullable<decimal> AskPx9 { get; set; }
        public Nullable<decimal> AskSz0 { get; set; }
        public Nullable<decimal> AskSz1 { get; set; }
        public Nullable<decimal> AskSz2 { get; set; }
        public Nullable<decimal> AskSz3 { get; set; }
        public Nullable<decimal> AskSz4 { get; set; }
        public Nullable<decimal> AskSz5 { get; set; }
        public Nullable<decimal> AskSz6 { get; set; }
        public Nullable<decimal> AskSz7 { get; set; }
        public Nullable<decimal> AskSz8 { get; set; }
        public Nullable<decimal> AskSz9 { get; set; }
        public System.DateTime Timestamp { get; set; }
    }
}
