//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chordata.Bex.Central.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Tuna : DbContext
    {
        public Tuna()
            : base("name=Tuna")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<API> APIs { get; set; }
        public virtual DbSet<OP> OPs { get; set; }
        public virtual DbSet<Symbol> Symbols { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Run> Runs { get; set; }
        public virtual DbSet<MarketHistory> MarketHistories { get; set; }
    }
}
