//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chordata.Bex.Central.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public string Exchange { get; set; }
        public string OrderId { get; set; }
        public string OrderType { get; set; }
        public string Side { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Symbol { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> ExecutionPrice { get; set; }
        public Nullable<decimal> ExecutionAmount { get; set; }
        public Nullable<System.DateTime> FilledDate { get; set; }
        public Nullable<System.DateTime> FullyFilledDate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string Comments { get; set; }
    }
}
