//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chordata.Bex.Central.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Run
    {
        public int Id { get; set; }
        public int OpId { get; set; }
        public string Text1 { get; set; }
        public string Text2 { get; set; }
        public string Text3 { get; set; }
        public string Text4 { get; set; }
        public string Text5 { get; set; }
        public string Text6 { get; set; }
        public string Text7 { get; set; }
        public string Text8 { get; set; }
        public string Text9 { get; set; }
        public string Text10 { get; set; }
        public string Text11 { get; set; }
        public string Text12 { get; set; }
        public string Text13 { get; set; }
        public string Text14 { get; set; }
        public string Text15 { get; set; }
        public Nullable<decimal> Num1 { get; set; }
        public Nullable<decimal> Num2 { get; set; }
        public Nullable<decimal> Num3 { get; set; }
        public Nullable<decimal> Num4 { get; set; }
        public Nullable<decimal> Num5 { get; set; }
        public Nullable<decimal> Num6 { get; set; }
        public Nullable<decimal> Num7 { get; set; }
        public Nullable<decimal> Num8 { get; set; }
        public Nullable<decimal> Num9 { get; set; }
        public Nullable<decimal> Num10 { get; set; }
        public Nullable<decimal> Num11 { get; set; }
        public Nullable<decimal> Num12 { get; set; }
        public Nullable<decimal> Num13 { get; set; }
        public Nullable<decimal> Num14 { get; set; }
        public Nullable<decimal> Num15 { get; set; }
        public Nullable<decimal> Num16 { get; set; }
        public Nullable<decimal> Num17 { get; set; }
        public Nullable<decimal> Num18 { get; set; }
        public Nullable<decimal> Num19 { get; set; }
        public Nullable<decimal> Num20 { get; set; }
        public Nullable<System.DateTime> Date1 { get; set; }
        public Nullable<System.DateTime> Date2 { get; set; }
        public Nullable<System.DateTime> Date3 { get; set; }
        public Nullable<System.DateTime> Date4 { get; set; }
        public Nullable<System.DateTime> Date5 { get; set; }
        public Nullable<System.DateTime> Date6 { get; set; }
        public Nullable<System.DateTime> Date7 { get; set; }
        public Nullable<System.DateTime> Date8 { get; set; }
        public string Order1 { get; set; }
        public string Order2 { get; set; }
        public string Order3 { get; set; }
        public string Order4 { get; set; }
        public string Order5 { get; set; }
        public string Order6 { get; set; }
        public string Progress { get; set; }
        public Nullable<System.DateTime> Started { get; set; }
        public Nullable<System.DateTime> Completed { get; set; }
        public Nullable<int> Status { get; set; }
        public string Message { get; set; }
    }
}
