//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chordata.Bex.Central.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Symbol
    {
        public int Id { get; set; }
        public string Exchange { get; set; }
        public string Name { get; set; }
        public string BaseCurrency { get; set; }
        public string QuoteCurrency { get; set; }
        public Nullable<bool> IsBaseFiat { get; set; }
        public Nullable<bool> IsQuoteFiat { get; set; }
        public string UnderlyingAsset { get; set; }
        public Nullable<bool> Enabled { get; set; }
        public Nullable<int> ExchangeId { get; set; }
        public Nullable<int> DecimalPlace { get; set; }
    }
}
